### ISSUE TITLE
command 'sortImports.sort' not found

### ISSUE THREAD

**Issue by JohanBeekers** [peterjuras/vsc-sort-imports#1]
I can't seem to get this to work. I installed this extension, opened a file with a bunch of imports, and then tried to execute the "Sort imports" command. But it gives me the error "command 'sortImports.sort' not found"

**Comment by peterjuras** [comment]
It looks like the command is not registered.

Is your active open editor a file with the .is extension and is the language in the lower right corner either JavaScript or JavaScript react?

Also which version of the extension and before are you using?

**Comment by JohanBeekers** [comment]
I'm using TypeScript actually. For which i assumed this would work...
And version 1.1.0 of this extension.

**Comment by peterjuras** [comment]
TypeScript is not supported right now, this extension is built on babel being able to parse the code, and babel can't parse TypeScript.

**Comment by JohanBeekers** [comment]
Hmm, such a shame. Oh well... i'll just have to live without this then. :)

**Comment by peterjuras** [comment]
Fixed with #2
