### ISSUE TITLE
Cursor is being moved to the end of the line after Save

### ISSUE THREAD

**Issue by brunolm** [peterjuras/vsc-sort-imports#11]
If I'm coding something and the cursor (`|`) is like this:

```
const { hash| } = parseUri(window.location.href);
```

After I save the cursor gets moved to the end of the line

```
const { hash } = parseUri(window.location.href);|
```

This is a little bit annoying for me because I have auto-save (VSCode) on and also sort on save, so if I tab out of the file the cursor gets messed up.

I would be really nice if the cursor position could be saved.

**Comment by peterjuras** [comment]
Hi!

Thanks for raising the issue, I'll try to look into it, but I have to see whether it is easily possible to preserve the cursor position due to the potential new lines that have been added.

**Comment by peterjuras** [comment]
This issue seems to apply to all text edit operations that are being performed on a save operation. ([See the issue in the vscode repository](https://github.com/Microsoft/vscode/issues/23733))

I hope there will be a resolution soon!

**Comment by pungggi** [comment]
Any progress in this? I love this extension, would be nice to solve this too. Thank you!

**Comment by peterjuras** [comment]
Hi, sadly it looks like there has been no progress made in this area. :( I will continue to monitor the [vscode issue](https://github.com/Microsoft/vscode/issues/23733) and update the status here once something changes.

**Comment by peterjuras** [comment]
Hi,

sadly I have to tell you that I can't work on this project anymore and I'm on the search for a new maintainer for this extension. Until then, this issue will likely remain unsovled.

**Comment by peterjuras** [comment]
This extension has been taken over by a new maintainer, please reopen your pull request under the [new repository.](https://github.com/amatiasq/vsc-sort-imports)
