### ISSUE TITLE
Comments moved when sort is executed

### ISSUE THREAD

**Issue by Martaver** [peterjuras/vsc-sort-imports#15]
I'm trying to apply a `//tslint:disable-line:no-import-side-effect` rule to one of my imports, and whenever sort-imports runs, the comment gets appended to the end of my entire import block.

It would be good if same-line comments would preserve their position relative to their import.

The most convenient version of this features would be to preserve any blank lines and comments before and on each import line. This would allow for the most flexibility, include documenting our imports, and adding tslint rules.

**Comment by tanya-coding** [comment]
The same if happening with license header comments at the top of the file.  +1!

**Comment by sketchthat** [comment]
Also happens if you have an import commented out like;
```typescript
// import { MyThing } from 'myPackage';
```

**Comment by peterjuras** [comment]
I released a new version of the extension, could you check again whether the comment moving behavior is still not working for you?

**Comment by sketchthat** [comment]
Doesn't appear to be working. I turned off all other extensions and tried;

```
import { b } from 'b';
// import { a } from 'a';
```
When I press save it converts to the following;

```
//import {
a
} from 'a';

**Comment by peterjuras** [comment]
Hi,

sadly I have to tell you that I can't work on this project anymore and I'm on the search for a new maintainer for this extension. Until then, this issue will likely remain unsovled.

**Comment by peterjuras** [comment]
This extension has been taken over by a new maintainer, please reopen your pull request under the [new repository.](https://github.com/amatiasq/vsc-sort-imports)
