### ISSUE TITLE
Groups on Top

### ISSUE THREAD

**Issue by acostaf** [peterjuras/vsc-sort-imports#17]
Hi Team

How can I stop sorting the groups in top of the file ?

**Comment by peterjuras** [comment]
By default, groups are sorted at the top. However, it is possible to customize the style of the import sorting. Please check out the [import-sort documentation](https://github.com/renke/import-sort#using-a-different-style-or-parser) for a style that could match your needs.

**Comment by acostaf** [comment]
thanks
