### ISSUE TITLE
Use import-sort v3.0.0

### ISSUE THREAD

**Issue by renke** [peterjuras/vsc-sort-imports#19]
Hi @peterjuras 

first of all, thank you very much for this extension! I finally added you to import-sort's README (about time if you ask me).

If you intent to use the new version, there is one (optional) change that I suggest you to look at:

The importSort now takes an optional 4th argument which is the absolute path to the file that is being sorted (see https://github.com/renke/import-sort/blob/master/packages/import-sort/src/index.ts#L19). 

The path can be used by styles to adapt the the actual sorting. For instance, this is used to respect the user's configuration of ESLint's sort-imports rule in the import-sort-style-eslint module.

Other than that, the API is the same. The new version only really contains some bug fixes and some other improvements. If you find any issue that I introduced with the new version, please let me know!

Best regards,
Renke

**Comment by peterjuras** [comment]
Hi Renke!

Thanks for the new version, it works great! I also added the absolute file path as a 4th argument in the newly released version.
