### ISSUE TITLE
Sorting case sensitivity

### ISSUE THREAD

**Issue by sketchthat** [peterjuras/vsc-sort-imports#20]
Is it expected behaviour that the import has case sensitivity.

```
import { a } from 'a';
import { b } from 'b';
import { C } from 'c';
import { D } from 'd';
```

Will convert to the below, shouldn't it stay as above?

```
import { C } from 'c';
import { D } from 'd';
import { a } from 'a';
import { b } from 'b';
```

**Comment by peterjuras** [comment]
Hi,

sadly I have to tell you that I can't work on this project anymore and I'm on the search for a new maintainer for this extension. Until then, this issue will likely remain unsovled.

**Comment by Frikki** [comment]
@sketchthat, no. Uppercase comes before lowercase. See the ASCII table: http://www.asciitable.com/

**Comment by peterjuras** [comment]
This extension has been taken over by a new maintainer, please reopen your pull request under the [new repository.](https://github.com/amatiasq/vsc-sort-imports)
