### ISSUE TITLE
The sorting order is in conflict with ts-lint

### ISSUE THREAD

**Issue by truhlikfredy** [peterjuras/vsc-sort-imports#21]
Code like this:
```
import TSAlignment         from "../src/tsalignment";
import * as basic          from "./dataBasicAlign";
import * as mixing         from "./dataMixing";
import * as regex          from "./dataRegex";
import { ITestUnitConfig } from "./testUnitConfigI";
import * as assert         from "assert";

```

Will get sorted wrongly:

https://stackoverflow.com/questions/41805723/how-to-order-imports-with-tslints-import-ordering-rule

**Comment by peterjuras** [comment]
Hi,

sadly I have to tell you that I can't work on this project anymore and I'm on the search for a new maintainer for this extension. Until then, this issue will likely remain unsovled.

**Comment by truhlikfredy** [comment]
That's OK. When I sort out my life I could become one. But that is questionable when that happens. Eventually I could try to make pull request if I will implement it myself

**Comment by alextreppass** [comment]
Related, paths with `_` in the name seem to be sorted incorrectly, i.e. ts-lint-valid:

```ts
import { Baz } from './foo/baz';
import { Bar } from './foo_bar/bar';
```

becomes:
```ts
import { Bar } from './foo_bar/bar';
import { Baz } from './foo/baz';
```

**Comment by peterjuras** [comment]
This extension has been taken over by a new maintainer, please reopen your pull request under the [new repository.](https://github.com/amatiasq/vsc-sort-imports)

**Comment by alextreppass** [comment]
Thanks but the new repo doesn’t allow issues
