### ISSUE TITLE
vscode Insiders error: Could not sort imports. - TypeError: style is not a function

### ISSUE THREAD

**Issue by kobenauf** [peterjuras/vsc-sort-imports#23]
Running Visual Source Code - Insiders, whenever I save my file, which triggers the sort, I get this Warning:
Could not sort imports. - TypeError: style is not a function

This happens in every file I save.

**Comment by peterjuras** [comment]
This extension has been taken over by a new maintainer, please reopen your pull request under the [new repository.](https://github.com/amatiasq/vsc-sort-imports)
