### ISSUE TITLE
support for dynamic import() syntax

### ISSUE THREAD

**Issue by iFwu** [peterjuras/vsc-sort-imports#24]
Thanks for creating this extension.
When trying to sort dynamic import syntax like `import('sth')`, it throws a warning:
```
Could not sort imports. - SyntaxError: Unexpected token (4:13)
```

I think there is a better way to handle this syntax.

**Comment by peterjuras** [comment]
This extension has been taken over by a new maintainer, please reopen your pull request under the [new repository.](https://github.com/amatiasq/vsc-sort-imports)
