### ISSUE TITLE
Error with // comment

### ISSUE THREAD

**Issue by poorbug** [peterjuras/vsc-sort-imports#25]
Before sorting: 
<img width="991" alt="2017-09-20 11 55 50" src="https://user-images.githubusercontent.com/5172464/30626203-e0199f62-9dfa-11e7-8b95-3ca88d7dcfbb.png">

After sorting:
<img width="854" alt="2017-09-20 11 56 01" src="https://user-images.githubusercontent.com/5172464/30626215-f4bb361a-9dfa-11e7-8a23-b418c00b570e.png">

**Comment by peterjuras** [comment]
This extension has been taken over by a new maintainer, please reopen your pull request under the [new repository.](https://github.com/amatiasq/vsc-sort-imports)
