### ISSUE TITLE
Add directory when calling import-sort-config's getConfig

### ISSUE THREAD

**Issue by renke** [peterjuras/vsc-sort-imports#4]
Hi there (author of import-sort here),

first of all, thanks for creating an extension for Visual Studio Code that uses import-sort!

To support custom styles it would be really nice, if you could add the file's directory (or the directory of the workspace) to the getConfig invocation (https://github.com/peterjuras/vsc-sort-imports/blob/master/src/sort.ts#L22).

If I can make it, I will provide a PR, but I can't promise it. In either case, I just wanted to let you know about this "issue" so it will be fixed eventually.

Best regards,
Renke

**Comment by peterjuras** [comment]
Thanks for your pull request! The ability to customize the styling of the imports can be very usefui for users.
