### ISSUE TITLE
Silence warning about SyntaxErrors

### ISSUE THREAD

**Issue by poislagarde** [peterjuras/vsc-sort-imports#7]
I'm being nagged by this (very useful!) extension when saving incomplete or otherwise invalid code, i.e.
> Could not sort imports. - SyntaxError: Unexpected token (53:0)

I save all the time during development before the code is ready, and it's becoming painful to dismiss these messages all the time. 

Maybe they can be disabled with a setting, moved to the output panel, or completely removed.

What do you think?

**Comment by peterjuras** [comment]
I feel your pain! While I am hesitant to change the default behavior (I think the extension should let the user know that sorting imports failed if sorting on save is enabled), I will add a setting to disable it.

**Comment by peterjuras** [comment]
Fixed with 651eb2b0ec1607e764ac4bb08ce1e07e7eee890a

After updating to version 2.2.0 you can set `sortImports.suppressWarnings` to `true` in your user settings to hide the warnings.

**Comment by poislagarde** [comment]
@peterjuras woah, that was fast! Thank you!
